let colors = ["red", "blue", "green", "yellow", "purple"];
console.log(colors);
colors.push("orange");
console.log(colors);
colors.pop();
console.log(colors);
colors.unshift("pink");
console.log(colors);
colors.shift();
console.log(colors);
